name: Publish Docker image
on:
  push
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push internal api image
        uses: docker/build-push-action@v2
        with:
          context: ./internal-api
          file: ./internal-api/Dockerfile
          tags: ghcr.io/conradludgate/k8s-learning/internal-api:${{ github.sha }}
          push: true

      - name: Build and push external api image
        uses: docker/build-push-action@v2
        with:
          context: ./external-api
          file: ./external-api/Dockerfile
          tags: ghcr.io/conradludgate/k8s-learning/external-api:${{ github.sha }}
          push: true